import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/componentes/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_br">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
